export default [
  {
    name: "romaine lettuce",
    type: "base",
    tags: ["base", "vegetable", "lettuce"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "baby spinach",
    type: "base",
    tags: ["base", "vegetable", "spinach"],
    weight: 0.5,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "kale",
    type: "base",
    tags: ["base", "vegetable", "kale"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "arugula",
    type: "base",
    tags: ["base", "vegetable", "arugula"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "mixed greens",
    type: "base",
    tags: ["base", "vegetable", "mixed greens"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "spring mix",
    type: "base",
    tags: ["base", "vegetable", "spring mix"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "iceberg lettuce",
    type: "base",
    tags: ["base", "vegetable", "lettuce"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "red leaf lettuce",
    type: "base",
    tags: ["base", "vegetable", "lettuce"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "butter lettuce",
    type: "base",
    tags: ["base", "vegetable", "lettuce"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "tomato",
    type: "topping",
    tags: ["topping", "vegetable", "tomato", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "cucumber",
    type: "topping",
    tags: ["topping", "vegetable", "cucumber", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "carrot",
    type: "topping",
    tags: ["topping", "vegetable", "carrot", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "red onion",
    type: "topping",
    tags: ["topping", "vegetable", "onion", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "green onion",
    type: "topping",
    tags: ["topping", "vegetable", "onion", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "bell pepper",
    type: "topping",
    tags: ["topping", "vegetable", "bell pepper", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "broccoli",
    type: "topping",
    tags: ["topping", "vegetable", "broccoli", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "cauliflower",
    type: "topping",
    tags: ["topping", "vegetable", "cauliflower", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "radish",
    type: "topping",
    tags: ["topping", "vegetable", "radish", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "celery",
    type: "topping",
    tags: ["topping", "vegetable", "celery", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "avocado",
    type: "topping",
    tags: ["topping", "vegetable", "avocado", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "mushroom",
    type: "topping",
    tags: ["topping", "vegetable", "mushroom", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "crispy fried onion",
    type: "topping",
    tags: ["topping", "vegetable", "onion", "fried", "crunchy", "pre packaged"],
    weight: 10,
    likesTags: [],
    dislikesTags: [{ tag: "crunchy", weight: 10 }],
  },
  {
    name: "sun dried tomato",
    type: "topping",
    tags: ["topping", "vegetable", "tomato", "dried", "pre packaged"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "sauteed mushroom",
    type: "topping",
    tags: ["topping", "vegetable", "mushroom", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "sauteed onion",
    type: "topping",
    tags: ["topping", "vegetable", "onion", "hot"],
    weight: 1,
    likesTags: [{ tag: "hot", weight: 5 }],
    dislikesTags: [],
  },
  {
    name: "grilled bell pepper",
    type: "topping",
    tags: ["topping", "vegetable", "bell pepper", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled zucchini",
    type: "topping",
    tags: ["topping", "vegetable", "zucchini", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled eggplant",
    type: "topping",
    tags: ["topping", "vegetable", "eggplant", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled asparagus",
    type: "topping",
    tags: ["topping", "vegetable", "asparagus", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled corn",
    type: "topping",
    tags: ["topping", "vegetable", "corn", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled squash",
    type: "topping",
    tags: ["topping", "vegetable", "squash", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled onion",
    type: "topping",
    tags: ["topping", "vegetable", "onion", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled tomato",
    type: "topping",
    tags: ["topping", "vegetable", "tomato", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled mushroom",
    type: "topping",
    tags: ["topping", "vegetable", "mushroom", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled pineapple",
    type: "topping",
    tags: ["topping", "fruit", "pineapple", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled apple",
    type: "topping",
    tags: ["topping", "fruit", "apple", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled pear",
    type: "topping",
    tags: ["topping", "fruit", "pear", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled peach",
    type: "topping",
    tags: ["topping", "fruit", "peach", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled mango",
    type: "topping",
    tags: ["topping", "fruit", "mango", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled watermelon",
    type: "topping",
    tags: ["topping", "fruit", "watermelon", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "ranch dressing",
    type: "dressing",
    tags: ["dressing", "ranch"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "peanut sauce",
    type: "dressing",
    tags: ["dressing", "sauce", "peanut"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "tahini sauce",
    type: "dressing",
    tags: ["dressing", "sauce", "tahini"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "hummus",
    type: "dressing",
    tags: ["dressing", "sauce", "hummus"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "tzatziki sauce",
    type: "dressing",
    tags: ["dressing", "sauce", "tzatziki"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "asian ginger dressing",
    type: "dressing",
    tags: ["dressing", "asian", "ginger"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "caesar dressing",
    type: "dressing",
    tags: ["dressing", "caesar"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "italian dressing",
    type: "dressing",
    tags: ["dressing", "italian"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "balsamic vinaigrette",
    type: "dressing",
    tags: ["dressing", "balsamic"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "honey mustard dressing",
    type: "dressing",
    tags: ["dressing", "honey mustard"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "thousand island dressing",
    type: "dressing",
    tags: ["dressing", "thousand island"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "blue cheese dressing",
    type: "dressing",
    tags: ["dressing", "blue cheese"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "feta cheese",
    type: "topping",
    tags: ["topping", "cheese", "feta", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "cheddar cheese",
    type: "topping",
    tags: ["topping", "cheese", "cheddar", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "mozzarella cheese",
    type: "topping",
    tags: ["topping", "cheese", "mozzarella", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "parmesan cheese",
    type: "topping",
    tags: ["topping", "cheese", "parmesan", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "goat cheese",
    type: "topping",
    tags: ["topping", "cheese", "goat", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "blue cheese",
    type: "topping",
    tags: ["topping", "cheese", "blue cheese", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "walnut",
    type: "topping",
    tags: ["topping", "nut", "walnut", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "almond",
    type: "topping",
    tags: ["topping", "nut", "almond", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "cashew",
    type: "topping",
    tags: ["topping", "nut", "cashew", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "pecan",
    type: "topping",
    tags: ["topping", "nut", "pecan", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "peanut",
    type: "topping",
    tags: ["topping", "nut", "peanut", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "pistachio",
    type: "topping",
    tags: ["topping", "nut", "pistachio", "cold"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "BBQ sauce",
    type: "dressing",
    tags: ["dressing", "sauce", "BBQ"],
    weight: 0.5,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "hot sauce",
    type: "dressing",
    tags: ["dressing", "sauce", "spicy"],
    weight: 0.5,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "italian croutons",
    type: "topping",
    tags: ["topping", "bread", "crunchy", "italian", "pre packaged"],
    weight: 10,
    likesTags: [],
    dislikesTags: [{ tag: "crunchy", weight: 10 }],
  },
  {
    name: "cheetos",
    type: "topping",
    tags: ["topping", "crunchy", "cheese", "pre packaged"],
    weight: 10,
    likesTags: [],
    dislikesTags: [{ tag: "crunchy", weight: 10 }],
  },
  {
    name: "doritos",
    type: "topping",
    tags: ["topping", "crunchy", "cheese", "pre packaged"],
    weight: 10,
    likesTags: [],
    dislikesTags: [{ tag: "crunchy", weight: 10 }],
  },
  {
    name: "tortilla strips",
    type: "topping",
    tags: ["topping", "crunchy", "corn", "pre packaged"],
    weight: 10,
    likesTags: [],
    dislikesTags: [{ tag: "crunchy", weight: 10 }],
  },
  {
    name: "sauteed garlic",
    type: "topping",
    tags: ["topping", "vegetable", "garlic", "hot"],
    weight: 1,
    likesTags: [{ tag: "hot", weight: 5 }],
    dislikesTags: [],
  },
  {
    name: "toasted pizza pieces",
    type: "topping",
    tags: ["topping", "bread", "crunchy", "pizza", "unusual"],
    weight: 0.1,
    likesTags: [{ tag: "pizza", weight: 10 }],
    dislikesTags: [{ tag: "crunchy", weight: 10 }],
  },
  {
    name: "crispy bacon",
    type: "topping",
    tags: ["topping", "meat", "bacon", "crunchy"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled chicken",
    type: "topping",
    tags: ["topping", "meat", "chicken", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled steak",
    type: "topping",
    tags: ["topping", "meat", "steak", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled salmon",
    type: "topping",
    tags: ["topping", "meat", "fish", "salmon", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled shrimp",
    type: "topping",
    tags: ["topping", "meat", "shrimp", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled pork",
    type: "topping",
    tags: ["topping", "meat", "pork", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled lamb",
    type: "topping",
    tags: ["topping", "meat", "lamb", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "grilled tofu",
    type: "topping",
    tags: ["topping", "meat", "tofu", "hot"],
    weight: 1,
    likesTags: [],
    dislikesTags: [],
  },
  {
    name: "pizza seasoning",
    type: "topping",
    tags: ["topping", "spice", "pizza", "unusual"],
    weight: 0.1,
    likesTags: [{ tag: "pizza", weight: 10 }],
    dislikesTags: [],
  },
  {
    name: "taco seasoning",
    type: "topping",
    tags: ["topping", "spice", "taco", "unusual"],
    weight: 0.1,
    likesTags: [{ tag: "taco", weight: 10 }],
    dislikesTags: [],
  },
  {
    name: "italian seasoning",
    type: "topping",
    tags: ["topping", "spice", "italian", "unusual"],
    weight: 0.1,
    likesTags: [{ tag: "italian", weight: 10 }],
    dislikesTags: [],
  },
];
